routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', [
	'uses' => 'FeedsController@homepage',
	'as' => 'homepage'
]);

Route::any('/login', [
	'uses' => 'UsersController@login',
	'as' => 'login'
]);
Route::any('/logout', [
	'uses' => 'UsersController@logout',
	'as' => 'logout'
]);

Route::group(['middleware'=>'auth', 'prefix'=>'admin'], function() {
	Route::get('/', [
		'uses' => 'FeedsController@dashboard',
		'as' => 'admin.dashboard'
	]);
	Route::any('/changepassword', [
		'uses' => 'UsersController@changePassword',
		'as' => 'admin.changepassword'
	]);
	Route::resource('feeds', 'FeedsController');
	Route::resource('categories', 'CategoriesController');
});

app/Feed.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Feed extends Model
{
    protected $fillable = [
        'provider_id', 'provider_name', 'provider_url',
        'feed_title', 'feed_description', 'feed_url', 'utc_time'
    ];

    protected $dates = ['utc_time'];

    protected $table = 'feeds';

    public function feedProvider()
    {
        return $this->belongsTo('App\FeedProvider', 'provider_id');
    }

    public function getUtcTimeAttribute($value)
    {
        $date = new \DateTime($value . ' +0000');
        $date->setTimezone(new \DateTimeZone(config('app.timezone')));
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/FeedsController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Feed;
use App\FeedProvider;
use Illuminate\Http\Request;

class FeedsController extends Controller
{
    public function homepage()
    {
        $categories = Category::get()->pluck('name', 'id');
        $feeds = Feed::limit(100)->orderBy('utc_time', 'desc');
        if (request()->input('filter')) {
            $category = request()->input('filter');
            $feeds->join('feeds_categories', function ($q) use ($category) {
                $q->whereRaw('feeds_categories.feed_id = feeds.provider_id');
                $q->where('feeds_categories.category_id', $category);
            });
        }
        $feeds = $feeds->get();
        return view('feeds.homepage', ['categories' => $categories, 'feeds'=>$feeds]);
    }



    // Admin methods

    public function dashboard()
    {
        return view('feeds.dashboard');
    }

    // Admin CRUD

    public function index()
    {
        if (Category::count() == 0) {
            return redirect()->route('categories.index')->with(
                ['message'=>'Before adding feed provider, please create atleast one category']
            );
        }

        $feeds = FeedProvider::get();

        return view('feeds.index', [ 'feeds' => $feeds]);
    }

    public function create()
    {
        $categories = Category::get()->pluck('name', 'id');
        return view('feeds.create', ['categories' => $categories]);
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'url' => 'required|url',
            'category' => 'required'
        ]);

        $feed = FeedProvider::create([
            'url' => $request->input('url')
        ]);
        $feed->categories()->sync($request->input('category'));
        return redirect()->route('feeds.index');
    }

    public function edit($id)
    {
        $categories = Category::get()->pluck('name', 'id');
        $feed = FeedProvider::where('id', $id)->first();
        $selectedCategories = $feed->categories()->get()->pluck('id')->toArray();
        return view('feeds.edit', [
            'feed' => $feed, 'categories' => $categories,
            'selectedCategories' => $selectedCategories
        ]);
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'url' => 'required|url',
            'category' => 'required'
        ]);

        $feed = FeedProvider::where('id', $id)->first();
        $feed->fill($request->all())->save();
        $feed->categories()->sync($request->input('category'));

        return redirect()->route('feeds.index');
    }

    public function destroy($id)
    {
        $feed = FeedProvider::where('id', $id)->first();
        $feed->categories()->detach();
        $feed->feeds()->delete();
        $feed->delete();
        return redirect()->route('feeds.index');
    }
}

resources/views/feeds/_nav.blade.php
<ul>
<li><a href="{{ route('feeds.index') }}">Feed Providers</a></li>
<li><a href="{{ route('categories.index') }}">Feed Categories</a></li>
</ul>

resources/views/feeds/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="panel panel-default">
	<div class="panel-heading">
		Create feed provider
	</div>
	<div class="panel-body">
		
		@include('partials.errors')

		<form action="{{ route('feeds.store') }}" method="POST">
			{{ method_field('POST') }}
			{{ csrf_field() }}
			<div class="form-group">
				<label for="url">Feed provider rss feed url</label>
				<input type="text" value="{{ old('url') }}" name="url" class="form-control" placeholder="http://www.delfi.lt/rss/feeds/daily.xml" required>
			</div>
			<div class="form-group">
				@foreach($categories as $id=>$name)
					<input type="checkbox" name="category[]" value="{{ $id }}"> {{ $name }}
				@endforeach
			</div>
			<button type="submit" class="btn btn-primary">Create</button>
			<a href="{{ route('feeds.index') }}" class="btn btn-warning">Cancel</a>
		</form>		
	</div>
</div>
@endsection

resources/views/feeds/dashboard.blade.php
@extends('layouts.admin')

@section('content')
	<div class="panel panel-default">
		<div class="panel-heading">
			RSS Feeds admin panel
		</div>
		<div class="panel-body">
		</div>
	</div>

@endsection

resources/views/feeds/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="panel panel-default">
	<div class="panel-heading">
		Edit feed provider
	</div>
	<div class="panel-body">
		@include('partials.errors')
		
		<form action="{{ route('feeds.update', ['feed'=>$feed->id]) }}" method="POST">
			{{ method_field('PUT') }}
			{{ csrf_field() }}
			<div class="form-group">
				<label for="url">Feed provider rss feed url</label>
				<input value="{{ $feed->url }}" type="text" name="url" class="form-control" placeholder="http://www.delfi.lt/rss/feeds/daily.xml" required>
			</div>
		
			<div class="form-group">
				@foreach($categories as $id=>$name)
					<input type="checkbox" name="category[]" value="{{ $id }}" {{ in_array($id, $selectedCategories)?"checked":"" }}> {{ $name }}
				@endforeach
			</div>
			

			<button type="submit" class="btn btn-primary">Save</button>
			<a href="{{ route('feeds.index') }}" class="btn btn-warning">Cancel</a>
		</form>
	</div>
</div>
@endsection

resources/views/feeds/homepage.blade.php
@extends('layouts.app')

@section('content')
<script>
	function showModal(id) {
		$('#myModal .modal-link').attr('href', $('#'+id+' a').attr('href'));
		$('#myModal .modal-title').html($('#'+id+' a').html());
		$('#myModal .modal-body').html($('#'+id+' div').html());
		$('#myModal').modal();
	}
</script>

<div class="container">
		<div class="row">
			<div class="col-md-2">
				<div class="panel panel-default">
					<div class="panel-heading">
						Categories
					</div>	
					<div class="panel-body">
						<a href="{{ route('homepage') }}">All feeds</a><br/>
						@foreach($categories as $id=>$name)
							<a href="{{ route('homepage', ['filter'=>$id]) }}">{{ $name }}</a><br/>
						@endforeach
					</div>
				</div>
			</div>
			<div class="col-md-10">
				<div class="panel panel-default">
					<div class="panel-heading">
						RSS Feeds
					</div>
					<div class="panel-body">
					<!-- Button trigger modal -->
						<table class="table">
							@foreach($feeds as $feed)
								<tr>
									<td style="min-width: 200px;">
										<a target="_blank" href="{{ $feed->provider_url }}">{{ $feed->provider_name }}</a>
									</td>
									<td id="feed-{{ $feed->id }}">
										<a onclick="showModal('feed-{{$feed->id}}'); return false;" target="_blank" href="{{ $feed->feed_url }}">{{ $feed->feed_title }}</a>
										<div style="display: none;">
											{{ $feed->feed_description }}
										</div>
									</td>
									<td style="width: 150px;">
										{{ $feed->utc_time }}
									</td>
								</tr>
							@endforeach

						</table>
					</div>
				</div>
			</div>
		</div>
	</div>


		<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <a href="" class="btn btn-primary modal-link" target="_blank">Go to feed page</a>
      </div>
    </div>
  </div>
</div>




@endsection

resources/views/feeds/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="panel panel-default">
	<div class="panel-heading">
		Feed providers
	</div>
	<div class="panel-body">

		<a class="btn btn-primary btn-xs" href="{{ route('feeds.create') }}">Create</a>

		<table class="table">
			<tr>
				<th>Url</th>
				<th style="width: 100px;">Actions</th>
			</tr>

			@foreach($feeds as $feed)
			<tr>
				<td>{{ $feed->url }}</td>
				<td>
					<form action="{{ route('feeds.destroy', ['feed'=>$feed->id]) }}" method="POST">
						<a class="btn btn-primary btn-xs" href="{{ route('feeds.edit', ['feed'=>$feed->id]) }}">edit</a>
						{{ csrf_field() }} {{ method_field('DELETE') }}
						<button class="btn btn-danger btn-xs" type="submit">delete</button>
					</form>
			@endforeach

		</table>
	</div>
</div>
@endsection